In [1]:
#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [2]:
data = pd.read_csv("../data/secondary_data.csv", sep = ";")
data.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,...,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,...,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,...,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,...,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,...,s,y,w,u,w,t,p,NaN,d,w

Can we predict the class of mushroom?

In [3]:
print(data.dtypes)

class                    object
cap-diameter            float64
cap-shape                object
cap-surface              object
cap-color                object
does-bruise-or-bleed     object
gill-attachment          object
gill-spacing             object
gill-color               object
stem-height             float64
stem-width              float64
stem-root                object
stem-surface             object
stem-color               object
veil-type                object
veil-color               object
has-ring                 object
ring-type                object
spore-print-color        object
habitat                  object
season                   object
dtype: object

In [4]:
#Dropping our columns with missing values
mushroom_data = data.dropna(axis = 1)
mushroom_data.head()

,class,cap-diameter,cap-shape,cap-color,does-bruise-or-bleed,gill-color,stem-height,stem-width,stem-color,has-ring,habitat,season
0,p,15.26,x,o,f,w,16.95,17.09,w,t,d,w
1,p,16.60,x,o,f,w,17.99,18.19,w,t,d,u
2,p,14.07,x,o,f,w,17.80,17.74,w,t,d,w
3,p,14.17,f,e,f,w,15.77,15.98,w,t,d,w
4,p,14.64,x,o,f,w,16.53,17.20,w,t,d,w

Going to make class, does-bruise-or-bleed, has-ring, and season as categorical

In [5]:
categorical_cols = ['class', 'does-bruise-or-bleed', 'has-ring', 'season']
mushroom_data[categorical_cols] = mushroom_data[categorical_cols].astype("category")
print(mushroom_data.dtypes)

class                   category
cap-diameter             float64
cap-shape                 object
cap-color                 object
does-bruise-or-bleed    category
gill-color                object
stem-height              float64
stem-width               float64
stem-color                object
has-ring                category
habitat                   object
season                  category
dtype: object

/tmp/ipykernel_4510/3476686096.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mushroom_data[categorical_cols] = mushroom_data[categorical_cols].astype("category")

In [6]:
# Standardizing our numeric variables
mushroom_data[["stem-height","cap-diameter","stem-width"]]= StandardScaler().fit_transform(mushroom_data[["stem-height","cap-diameter","stem-width"]])

/tmp/ipykernel_4510/1553499946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mushroom_data[["stem-height","cap-diameter","stem-width"]]= StandardScaler().fit_transform(mushroom_data[["stem-height","cap-diameter","stem-width"]])

In [8]:
# Only want to keep categorical and numerical, don't want to keep objects
mushroom_data = mushroom_data.loc[:, ['class', 'does-bruise-or-bleed', 'has-ring', 'season', 'stem-height', 'cap-diameter', 'stem-width']]
mushroom_data.head()

,class,does-bruise-or-bleed,has-ring,season,stem-height,cap-diameter,stem-width
0,p,f,t,w,3.076705,1.619462,0.492293
1,p,f,t,u,3.385311,1.873982,0.601900
2,p,f,t,w,3.328931,1.393432,0.557061
3,p,f,t,w,2.726555,1.412426,0.381690
4,p,f,t,w,2.952075,1.501699,0.503254

In [11]:
mushroom_data_1h = pd.get_dummies(mushroom_data, columns=['class', 'does-bruise-or-bleed', 'has-ring', 'season'], drop_first=True)
mushroom_data_1h.head()

,stem-height,cap-diameter,stem-width,class_p,does-bruise-or-bleed_t,has-ring_t,season_s,season_u,season_w
0,3.076705,1.619462,0.492293,True,False,True,False,False,True
1,3.385311,1.873982,0.601900,True,False,True,False,True,False
2,3.328931,1.393432,0.557061,True,False,True,False,False,True
3,2.726555,1.412426,0.381690,True,False,True,False,False,True
4,2.952075,1.501699,0.503254,True,False,True,False,False,True

In [15]:
# Defining our independent/dependent variables
X = mushroom_data_1h.drop('class_p', axis=1)
y = mushroom_data_1h['class_p']

In [16]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.70, stratify = y, random_state=77)

In [18]:
# Model building
shroom_nn = KNeighborsClassifier(n_neighbors=7)
shroom_nn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
import warnings

accuracy = accuracy_score(y_test, shroom_nn.predict(X_test))

tn, fp, fn, tp = confusion_matrix(y_test, shroom_nn.predict(X_test)).ravel()
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

# Calculate F1 score
f1 = metrics.f1_score(y_test, shroom_nn.predict(X_test))

# Calculate cross entropy
cross_entropy = -np.mean(y_test * np.log(shroom_nn.predict_proba(X_test)[:, 1]) + (1 - y_test) * np.log(1 - shroom_nn.predict_proba(X_test)[:, 1]))

# Calculate ROC/AUC
roc_auc = roc_auc_score(y_test, shroom_nn.predict_proba(X_test)[:, 1])
fpr, tpr, thresholds = roc_curve(y_test, shroom_nn.predict_proba(X_test)[:, 1])

print('Accuracy:', accuracy)
print('TPR:', tpr)
print('FPR:', fpr)
print('F1 Score:', f1)
print('Cross Entropy:', cross_entropy)
print('ROC AUC:', roc_auc)
warnings.filterwarnings("ignore")

Accuracy: 0.8821025053217619
TPR: [0.         0.65496213 0.76826989 0.84538212 0.89780663 0.93596931
 0.96852562 0.98731189 1.        ]
FPR: [0.         0.01900908 0.04549914 0.08584744 0.13747854 0.19659063
 0.27618347 0.39502085 1.        ]
F1 Score: 0.8942006269592476
Cross Entropy: inf
ROC AUC: 0.9499769775579319

In [33]:
# Part 4. Consider where classification errors are occurring, is there a pattern? If so discuss this pattern and why you think this is the case.

Confusion Matrix:
[[7033 1121]
 [1039 9128]]
Classification Report:
              precision    recall  f1-score   support

       False       0.87      0.86      0.87      8154
        True       0.89      0.90      0.89     10167

    accuracy                           0.88     18321
   macro avg       0.88      0.88      0.88     18321
weighted avg       0.88      0.88      0.88     18321

NameError: name 'plot_confusion_matrix' is not defined

3. Since we are aiming to predict class of mushroom, positive and negatives matter equally. This means that we want to look at TPR and FPR with equal importance. Accuracy is very important as we want to see with what rate we can predict class of mushroom. Since we have so many observations our data is approximately normal, so we are not too concerned with f1 score.

Part 4. Consider where classification errors are occurring, is there a pattern? If so discuss this pattern and why you think this is the case.

In [35]:
# Calculate the predicted labels for the test set
y_pred = shroom_nn.predict(X_test)

# Create a confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate the classification report
report = metrics.classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Confusion Matrix:
[[7033 1121]
 [1039 9128]]
Classification Report:
              precision    recall  f1-score   support

       False       0.87      0.86      0.87      8154
        True       0.89      0.90      0.89     10167

    accuracy                           0.88     18321
   macro avg       0.88      0.88      0.88     18321
weighted avg       0.88      0.88      0.88     18321

There are more that are identified as true than false. This may have to do with higher levels of true.